### ISSUE TITLE
How to initialise keypoints.p

### ISSUE THREAD

**Issue by controlzone** [dan-masek/OCV_Vehicles_Features#1]
Hi
I am trying to get your code working under python 2.7 and opencv 3.0.0 but I am having some problems creating the _keypoints.p_ file - It doesn't seem like there is any place that the file is created / initialised with a default set of values. Could you please point me in the right direction?
Thanks

**Comment by dan-masek** [comment]
If I remember correctly (it's been a while since I played with this), you generate the file using the script `create_kd_sift.py`

**Comment by controlzone** [comment]
Wow I can't believe I missed that! 
Thank you
